site_name: Salas.com Some Stuff I just figured out
docs_dir: docs
nav:
    - Home: index.md
    - About: about.md
    - License: license.md
    - test: test.md
    - welcome: welcome.md
theme: material

